### ISSUE TITLE
Resizer is not working with vertical proroption

### ISSUE THREAD

**Issue by djvov** [fabrice8/cropimage#1]
if proroption (width / height) is < 1 (vertical) then resizer is not work... move but its width is 0
`
 $('#contain').resizeImage({
                                        image: 'pic',
imgFormat: '0.5/1', 
})
`
![Безымянный](https://user-images.githubusercontent.com/7313776/143494156-466a1eee-0370-47dc-a148-d24fc6bd2e12.png)

**Comment by fabrice8** [comment]
Hi @djvov. It has been a while since i touch the code so i slightly reorganised the repo including a fix for this issue. Give it a new try and let me know whether it works for you. Thanks for the feedback
