### ISSUE TITLE
Images are not showing correctly on load cutting edges from lower side of image

### ISSUE THREAD

**Issue by asif-ca** [fabrice8/cropimage#2]
Hi, your library looks great, however when we tried to implement we are facing these issues:

**Please check the attached images** 
![image](https://user-images.githubusercontent.com/86609190/208614150-d4f3df9a-663f-4103-893b-f82a88b3e6ea.png)

**And the original image is:**

![childs](https://user-images.githubusercontent.com/86609190/208614251-06015131-dea5-4b45-8908-aae8c5796d79.jpg)

_And this gets worse if we load the image in a modal_
**How can we fix these issues?**

**Comment by fabrice8** [comment]
Thanks for the feedback. A fix update is pushed and also published on npm. Kindly let me know if that works for you.

**Comment by asif-ca** [comment]
Thanks for the quick reply.

We also checked the attached image in your `test/index.html` files (Test project in your repository)
please use the attached image in your example code in place of horizontal.jpeg in `index.html`


However, we used the bootstrap modal and the **_height of the modal was 400px_**

**Comment by fabrice8** [comment]
Alright thanks for the suggestion. Is it well responsive with the modal now?

**Comment by asif-ca** [comment]
Hi, Thanks for your fix!

Things look much better now however we prepared a demo with the bootstrap modal and created a pull request (explaining issues), please have a look at that.

**Comment by asif-ca** [comment]
Hi, @fabrice8 were you able to replicate the issue?

**Comment by fabrice8** [comment]
Hi @asif-ca. I have replicated the issue but couldn't worked on a usable solution yet. I promise to fix it as soon as possible. Thanks

**Comment by fabrice8** [comment]
Fixed. Check `/test/modal` folder
