### ISSUE TITLE
resetting Cropper for a second image without reloading page

### ISSUE THREAD

**Issue by RichardPilks** [fabrice8/cropimage#5]
Good day
Firstly thank you for this lightweight image cropper.  I have been able to get it to work on my application.

I have a question:
I crop an image in a modal created for the purpose, and then display the image in the image list on the page.  When I upload a second image to crop, the result is stored with the first images copped result again.  I need to be able to clear out the image from cropimage when I have finished with an image.  Something like a reset or destroy function?
Can you tell me if there is something like that?

**Comment by fabrice8** [comment]
Good day @RichardPilks.

Thanks for the feedback.
I made an update [here](https://github.com/fabrice8/cropimage/commit/7af3addb9c6cd7ab456dbb159f2d40f9b28237a6) that should fix your problem.

Kindly install the new version and give it a try.

**Comment by RichardPilks** [comment]
Thank you for the quick response, @fabrice8 
I tried the updated plugin and I got an error on the second image saying: 
  "Configuration Error:  Undefined image URL or blob image file" 
on a black background when I cropped the image.
I have included some code to make sure I am using it correctly:  This is called after the image is uploaded and I detect it is not square (ratio !== 1)

```JS
const cropOptions = {   // SET UP THE OPTIONS
            image: options.src,
            imgFormat: '4/4', // Formats: 3/2, 200x360, auto
            zoomable: true,
            minHeight: 100,
            background: 'transparent',
            inBoundGrid: true
//                            btnDoneAttr: '#imageSquareModal .btn-primary'
        };
        let cropper = $('#imageSquareModal .contain').cropimage(cropOptions);  // CREATE IMAGE IN CONTAINER
        $("#cropImage").click(function() {  // 
            if(cropping) { // THIS WAS BECAUSE I GOT A DOUBLE SUBMISSION FOR THE IMAGE SAVE TO SERVER (NOT DEBUGGED YET)
                return;
            }
            cropping = true;
            const blobDataURL = cropper.getImage(options.type.toUpperCase()); // JPEG, PNG, ...
            $("#imageData").val(blobDataURL);
            $.ajax({
                url: '/product/fix-image',
                type: 'post',
                dataType: 'json',
                data: $("#imgSqrFrm").serialize(),
                success: function(response) {
                    if(response.success) {
                        addThumbnail(response);  // UPDATE THE IMAGE LIST
                        setTimeout(function(){  // ATTEMPT TO RESET OR REMOVE FIRST IMAGE SO IT DOES NOT APPEAR FOR THE SECOND
                            $('#imageSquareModal').modal('hide');
                            $("#imageData").val('');
                            $(".contain").html('');
                            cropper.reset();
                            cropping = false;
                        },500);
                    }
                    else {
                        alert(response.message);
                    }
                }
            });
        });
```

**Comment by RichardPilks** [comment]
Sorry I did not use the preview, I see it does not format it nicely.

**Comment by fabrice8** [comment]
> Sorry I did not use the preview, I see it does not format it nicely.

Can you share a screenshot of how it displays? 
Also share a snippet of your code to see if I can suggest some help around.

**Comment by RichardPilks** [comment]
My comment regarding the formatting not being nice was about formatting of the sample of code I posted.  There is nothing wrong with the formatting of images.

**Comment by RichardPilks** [comment]
I see in my posts I closed the issue by mistake when I reported that there was still a problem and provided sample code of how I use the plugin. I have not used Github issues before and clicked the wrong button to post my response.
I apologize for causing confusion and making it difficult for you.  I reopened the issue because It is not solved in my case.

**Comment by fabrice8** [comment]
> My comment regarding the formatting not being nice was about formatting of the sample of code I posted.  There is nothing wrong with the formatting of images.

Okay get it now.
I added the formating to the code for you then. You can click edit on that comment to see how it's done.

**Comment by fabrice8** [comment]
> I see in my posts I closed the issue by mistake when I reported that there was still a problem and provided sample code of how I use the plugin. I have not used Github issues before and clicked the wrong button to post my response.
> I apologize for causing confusion and making it difficult for you.  I reopened the issue because It is not solved in my case.

No problem.

Do you run the code you shared above every time your open the modal?

**Comment by RichardPilks** [comment]
Yes.  I need to upload and crop multiple images on the page before submitting the form.  I only crop the image if it is not square

**Comment by fabrice8** [comment]
Alright. Seems like anytime you run the code, the `$("#cropImage").click(...)` event listener is defined again and again. So even when you finished cropping and close the modal, the event is still listening. When you click on `#cropImage` trigger, it fire the event multiple times.

Keep anytime about the code intact but try to define the event independently from the modal trigger context. Then test and see whether you'll get the same issue.

**Comment by RichardPilks** [comment]
I have been away, sorry I have not responded.
I made the change to only create the trigger on page load.  I used your new reset function and the cropper now does what I expected.
Thank you again for the awesome plug-in, and much thanks for responding to my issue.
Regards  Richard
